version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
     - ${DB_PORT_IN_DOCKER}
  web:
    build: .
    command: python manage.py runserver ${RUN_PORT_IN_DOCKER}
    volumes:
      - .:/code
    ports:
      - ${APP_PORT_IN_DOCKER}
    depends_on:
      - db

  celery_worker:
    build: .

    command: celery -A captain_bot worker -B -l INFO
    volumes:
      - .:/code/
    links:
      - db
      - rabbit

  rabbit:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./docker/volumes/rabbit:/var/lib/rabbitmq
